#ifndef GEMINI_H
#define GEMINI_H

#include <Arduino.h>
#include <WiFiClientSecure.h>
#include <HTTPClient.h>
#include <ArduinoJson.h>
#include "Behaviour.h"

// Extern references for global variables and helpers in main.cpp
extern SemaphoreHandle_t geminiMutex;
extern String currentPrompt;
extern volatile bool lastResponseIsAi;
extern int lastTriggeredEventType;
extern String lastTriggeredEventDetail;
extern String aiResponse;
extern volatile bool hasNewAIResponse;
extern String currentUserName;
extern String userName;
extern int aiMode;
extern int dailyAiRequestCount;
extern unsigned long totalDeskTime;
extern unsigned long totalFocusTime;
extern unsigned long totalBreakTime;
extern int breakCount;
extern int productivityScore;
extern volatile bool isAILoading;

extern String formatTime(unsigned long ms);
extern String personalizeQuote(String quote, String name);

// Asynchronous FreeRTOS Task for Gemini HTTPS Queries
inline void queryGeminiTask(void * parameter) {
  xSemaphoreTake(geminiMutex, portMAX_DELAY);
  String prompt = currentPrompt;
  xSemaphoreGive(geminiMutex);

  bool success = false;
  WiFiClientSecure client;
  client.setInsecure(); // Disable SSL certificate verification for local speed
  
  HTTPClient https;
  String url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=" + String(GeminiApiKey);
  
  if (https.begin(client, url)) {
    https.addHeader("Content-Type", "application/json");
    
    // Build JSON request payload
    DynamicJsonDocument reqDoc(1024);
    reqDoc["contents"][0]["parts"][0]["text"] = prompt;
    String payload;
    serializeJson(reqDoc, payload);
    
    int httpCode = https.POST(payload);
    if (httpCode == 200) {
      String response = https.getString();
      DynamicJsonDocument respDoc(2048);
      DeserializationError error = deserializeJson(respDoc, response);
      if (!error) {
        String generatedText = respDoc["candidates"][0]["content"]["parts"][0]["text"].as<String>();
        generatedText.trim();
        
        // Remove enclosing quotes if generated by LLM
        if (generatedText.startsWith("\"") && generatedText.endsWith("\"")) {
          generatedText = generatedText.substring(1, generatedText.length() - 1);
        }
        
        xSemaphoreTake(geminiMutex, portMAX_DELAY);
        lastResponseIsAi = true;
        if (lastTriggeredEventType == EVENT_WELCOME_BACK || lastTriggeredEventType == EVENT_FIRST_SIT || lastTriggeredEventType == EVENT_STREAK_BEATEN) {
          char welcomeMsg[128];
          snprintf(welcomeMsg, sizeof(welcomeMsg), "%s (%s)", generatedText.c_str(), lastTriggeredEventDetail.c_str());
          aiResponse = String(welcomeMsg);
        } else {
          aiResponse = generatedText;
        }
        hasNewAIResponse = true;
        xSemaphoreGive(geminiMutex);
        success = true;
      }
    }
    https.end();
  }

  // Graceful fallback: If Gemini query fails, load a local fallback quote immediately
  if (!success) {
    const char* quote = "";
    int randIdx = random(20);
    switch (lastTriggeredEventType) {
      case EVENT_FIRST_SIT:     quote = localFirstSit[randIdx]; break;
      case EVENT_WELCOME_BACK:  quote = localWelcomeBack[randIdx]; break;
      case EVENT_STRETCH:       quote = localStretch[randIdx]; break;
      case EVENT_FOCUS_END:     quote = localFocus[randIdx]; break;
      case EVENT_SLACKER:       quote = localSlacker[randIdx]; break;
      case EVENT_STREAK_BEATEN: quote = localStreakBeaten[randIdx]; break;
      default:                  quote = localWelcomeBack[randIdx]; break;
    }
    
    xSemaphoreTake(geminiMutex, portMAX_DELAY);
    lastResponseIsAi = false;
    String nameCopy = currentUserName;
    xSemaphoreGive(geminiMutex);

    String personalQuote = personalizeQuote(String(quote), nameCopy);
    
    xSemaphoreTake(geminiMutex, portMAX_DELAY);
    if (lastTriggeredEventType == EVENT_WELCOME_BACK || lastTriggeredEventType == EVENT_FIRST_SIT || lastTriggeredEventType == EVENT_STREAK_BEATEN) {
      char welcomeMsg[128];
      snprintf(welcomeMsg, sizeof(welcomeMsg), "%s (%s)", personalQuote.c_str(), lastTriggeredEventDetail.c_str());
      aiResponse = String(welcomeMsg);
    } else {
      aiResponse = personalQuote;
    }
    hasNewAIResponse = true;
    xSemaphoreGive(geminiMutex);
  }
  
  isAILoading = false;
  vTaskDelete(NULL); // One-shot task deletion
}

// Coordinated behaviour trigger: runs background Gemini task or picks local fallback
inline void triggerBehaviour(int eventType, String detail = "") {
  lastTriggeredEventType = eventType;

  xSemaphoreTake(geminiMutex, portMAX_DELAY);
  lastTriggeredEventDetail = detail;
  currentUserName = userName;
  xSemaphoreGive(geminiMutex);

  bool useAI = false;
  if (aiMode == 2) {
    // Frequent mode: all events can trigger AI
    useAI = true;
  } else if (aiMode == 1) {
    // Balanced mode: AI triggers for FIRST_SIT, STRETCH, and WELCOME_BACK
    if (eventType == EVENT_FIRST_SIT || eventType == EVENT_STRETCH || eventType == EVENT_WELCOME_BACK) {
      useAI = true;
    }
  }

  // Enforce daily cap (max 15 requests per day)
  if (useAI && dailyAiRequestCount >= 15) {
    useAI = false;
  }

  if (useAI) {
    String basePrompt = "";
    char formattedPrompt[256];
    switch (eventType) {
      case EVENT_FIRST_SIT:
        snprintf(formattedPrompt, sizeof(formattedPrompt), PROMPT_FIRST_SIT_OF_DAY, userName.c_str(), detail.c_str());
        basePrompt = String(formattedPrompt);
        break;
      case EVENT_WELCOME_BACK:
        snprintf(formattedPrompt, sizeof(formattedPrompt), PROMPT_WELCOME_BACK, userName.c_str(), detail.c_str());
        basePrompt = String(formattedPrompt);
        break;
      case EVENT_STRETCH:
        snprintf(formattedPrompt, sizeof(formattedPrompt), PROMPT_STRETCH_REMINDER, userName.c_str());
        basePrompt = String(formattedPrompt);
        break;
      case EVENT_FOCUS_END:
        snprintf(formattedPrompt, sizeof(formattedPrompt), PROMPT_FOCUS_CONGRATS, userName.c_str(), detail.c_str());
        basePrompt = String(formattedPrompt);
        break;
      case EVENT_SLACKER:
        snprintf(formattedPrompt, sizeof(formattedPrompt), PROMPT_SLACKER_ROAST, userName.c_str());
        basePrompt = String(formattedPrompt);
        break;
      case EVENT_STREAK_BEATEN:
        snprintf(formattedPrompt, sizeof(formattedPrompt), PROMPT_STREAK_BEATEN, userName.c_str(), detail.c_str());
        basePrompt = String(formattedPrompt);
        break;
    }

    if (!isAILoading) {
      dailyAiRequestCount++;
      // Format details including Productivity Score & history
      String fullPrompt = basePrompt + "\nContext details:\n";
      fullPrompt += "User's Name: " + userName + "\n";
      fullPrompt += "At Desk Time: " + formatTime(totalDeskTime) + "\n";
      fullPrompt += "Focus Time: " + formatTime(totalFocusTime) + "\n";
      fullPrompt += "Break Time: " + formatTime(totalBreakTime) + "\n";
      fullPrompt += "Breaks taken: " + String(breakCount) + "\n";
      fullPrompt += "Productivity Score: " + String(productivityScore) + "%\n";
      fullPrompt += "Instruction: Address the user as " + userName + ". Respond with one short, witty sentence in English or Portuguese under 30 characters.";

      xSemaphoreTake(geminiMutex, portMAX_DELAY);
      currentPrompt = fullPrompt;
      xSemaphoreGive(geminiMutex);
      
      isAILoading = true;
      xTaskCreate(
        queryGeminiTask,
        "GeminiQuery",
        8192,
        NULL,
        1,
        NULL
      );
    }
  } else {
    // Local Fallback selection (picks from 20 available per event type)
    const char* quote = "";
    int randIdx = random(20);
    switch (eventType) {
      case EVENT_FIRST_SIT:     quote = localFirstSit[randIdx]; break;
      case EVENT_WELCOME_BACK:  quote = localWelcomeBack[randIdx]; break;
      case EVENT_STRETCH:       quote = localStretch[randIdx]; break;
      case EVENT_FOCUS_END:     quote = localFocus[randIdx]; break;
      case EVENT_SLACKER:       quote = localSlacker[randIdx]; break;
      case EVENT_STREAK_BEATEN: quote = localStreakBeaten[randIdx]; break;
    }

    String personalQuote = personalizeQuote(String(quote), userName);

    // Immediately post fallback quote to display thread-safely
    xSemaphoreTake(geminiMutex, portMAX_DELAY);
    lastResponseIsAi = false;
    if (eventType == EVENT_WELCOME_BACK || eventType == EVENT_FIRST_SIT || eventType == EVENT_STREAK_BEATEN) {
      char welcomeMsg[128];
      snprintf(welcomeMsg, sizeof(welcomeMsg), "%s (%s)", personalQuote.c_str(), detail.c_str());
      aiResponse = String(welcomeMsg);
    } else {
      aiResponse = personalQuote;
    }
    hasNewAIResponse = true;
    xSemaphoreGive(geminiMutex);
  }
}

#endif // GEMINI_H
